/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Account: typeof import('./src/components/account.vue')['default']
    Transfer: typeof import('./src/components/transfer.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanDivider: typeof import('vant/es')['Divider']
    Web3Api: typeof import('./src/components/Web3Api.vue')['default']
  }
}
